### ISSUE TITLE
Brickly - Joystick Buttons are not detected

### ISSUE THREAD

**Issue by PeterDHabermehl** [harbaum/cfw-apps#3]
Hi Till,
now that my gamepad is finally detected by the cfw, I found that the buttons are not detected at all by Brickly.
In the joytest app they are shown, so basically it seems to work.
The sticks do work, though. So I could already remote-control our robot. Thanks for that!!!

Peter

**Comment by harbaum** [comment]
None of the various button in the input block reacts on any of the buttons of your gamepad?

If you log into your TXT and run jstest /dev/input/js0 the names of the buttons and axes will be displayed. And you can see which name each button has when you press it.

**Comment by PeterDHabermehl** [comment]
Good, will do so later total.
Thx Peter

**Comment by PeterDHabermehl** [comment]
So here's the answer: no, it doesn't.

> $ ./jstest.py /dev/input/js0
QVNCScreen could not attach to shared memory: "QSharedMemory::handle: UNIX key file doesn't exist" 

that's the complete output... No axes, no buttons. All actions are displayed in the UI correctly, though...

**Comment by harbaum** [comment]
Not my jstest.py. the systems jstest

**Comment by PeterDHabermehl** [comment]
> $ jstest
-sh: jstest: not found

I tried before since you did not explicitly write **_./jstest.py_** but rather **_jstest /dev/input/js0_**...

**Comment by harbaum** [comment]
Ok ... then there's no jstest on the txt. Maybe i built mine myself ....

**Comment by PeterDHabermehl** [comment]
ok, did a jstest on suse42.2: 

> Axes:  0:     0  1:     0  2:     0  3:     0  4:-32767  5:-32767  6:     0  7:     0 Buttons:  0:off  1:off  2:off  3:off  4:off  5:off  6:off  7:off  8:off  9:off 10:off 11:off 12:off 13:off 14:off 

Axes 4 and 5 do not exist, 0/1 is the left analogue stick, 2/3 is the right analogue stick (not found by jstest.py), 6/7 is the left digital hat (right stick in jstest.py)
All buttons do work, but I found no name output, sry.
Maybe you should just map the button numbers to brickly inputs (knopf 1..x)
Kind regards,
Peter

**Comment by PeterDHabermehl** [comment]
Fixed!
