### ISSUE TITLE
TXT and python

### ISSUE THREAD

**Issue by tailindu** [harbaum/cfw-apps#6]
Hello,dear friend! I know python,but i don't know how to programme on the TXT controller by python. If you know that, please  send me a  instruction,thank you so much!（1012157429@qq.com）

**Comment by harbaum** [comment]
Python programming instructions are here: https://cfw.ftcommunity.de/ftcommunity-TXT/en/programming/python/

**Comment by tailindu** [comment]
Got it .Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Till Harbaum"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 下午3:53
收件人:&nbsp;"harbaum/cfw-apps"<cfw-apps@noreply.github.com&gt;;
抄送:&nbsp;"【度】"<1012157429@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [harbaum/cfw-apps] TXT and python (#6)





 
Python programming instructions are here: https://cfw.ftcommunity.de/ftcommunity-TXT/en/programming/python/
